version: '3.9'

services:
  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 5

  createbuckets:
    image: minio/mc
    restart: on-failure
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      echo 'Wait 15s until MinIO boots up';
      sleep 15;
      mc config host add myminio http://minio:9000 minioadmin minioadmin;
      mc mb myminio/filesystem;
      mc anonymous set public myminio/filesystem;  #can be public here, in prod it shouldn't
      exit 0;
      "

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: sftpgo
      POSTGRES_PASSWORD: sftpgo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "sftpgo"]
      interval: 30s
      timeout: 10s
      retries: 5

  sftpgo:
    image: drakkan/sftpgo
    container_name: sftpgo
    depends_on:
      createbuckets:
        condition: service_completed_successfully
    environment:
      SFTPGO_DEFAULT_ADMIN_USERNAME: admin
      SFTPGO_DEFAULT_ADMIN_PASSWORD: admin
      SFTPGO_HTTPD__BINDINGS__0__PORT: 8080
      SFTPGO_DATA_PROVIDER__DRIVER: postgresql
      SFTPGO_DATA_PROVIDER__NAME: sftpgo
      SFTPGO_DATA_PROVIDER__HOST: postgres
      SFTPGO_DATA_PROVIDER__PORT: 5432
      SFTPGO_DATA_PROVIDER__USERNAME: sftpgo
      SFTPGO_DATA_PROVIDER__PASSWORD: sftpgo
    ports:
      - "2022:2022"
      - "8080:8080"
    volumes:
      - sftpgo_data:/var/lib/sftpgo
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/v1/ping"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  shared-data:
    driver: local
  minio_data:
  postgres_data:
  sftpgo_data: